import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// In dev mode, copy build output into the bundled test vault so Obsidian
// (with the Hot-Reload plugin) picks up changes automatically.
const TEST_VAULT_PLUGIN_DIR = 'test-vault/.obsidian/plugins/always-be-closing';
const copyToTestVault = {
	name: 'copy-to-test-vault',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			mkdirSync(TEST_VAULT_PLUGIN_DIR, { recursive: true });
			for (const file of ['main.js', 'manifest.json', 'styles.css']) {
				if (existsSync(file)) copyFileSync(file, join(TEST_VAULT_PLUGIN_DIR, file));
			}
			// Marker file that tells Hot-Reload to watch this plugin.
			writeFileSync(join(TEST_VAULT_PLUGIN_DIR, '.hotreload'), '');
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		// jsPDF loads these only for its html()/SVG features, which the plugin doesn't use.
		'html2canvas',
		'dompurify',
		'canvg',
		...builtinModules,
	],
	// Fonts for PDFs are inlined as base64 strings (see src/pdf/fonts.ts).
	loader: { '.ttf': 'base64' },
	define: {
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
	},
	jsx: 'automatic',
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: prod ? [] : [copyToTestVault],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
